[workspace]
members = [
    "ofborg",
    "ofborg-simple-build"
]
resolver = "2"

[profile.release]
debug = true

[patch.crates-io]
#hubcaps = { path = "../hubcaps" }
#amq-proto = { path = "rust-amq-proto" }
